# This Docker-Compose file would be used on the server to deploy 
# all the applications/services

version: '3'
services:

  python:
    container_name: py-app-users
    image: app-api-users:0.9.1
    depends_on: 
      - mongodb
    ports:
      - 5000:5000
    environment:
      - JWT_SECRET=jwtsecret
      - MONGODB_DATABASE=usersdb
      - MONGODB_USERNAME=xarmando
      - MONGODB_PASSWORD=12345
      - MONGODB_HOSTNAME=mongodb
      - MONGODB_PORT=27017
  mongodb:
    container_name: mongo
    command: mongod --auth
    image: mongo
    ports:
      - 27017:27017
    environment:
    #super admin user
      - MONGO_INITDB_ROOT_USERNAME=myAdmin
      - MONGO_INITDB_ROOT_PASSWORD=secret
      - MONGO_INITDB_DATABASE=usersdb
    volumes:
      - mongo-data:/data/db

#It's not required, a better tool is MongoDB Compass.
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    depends_on:
      - mongodb
    ports: 
      - 8080:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=myAdmin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=secret
      - ME_CONFIG_MONGODB_SERVER=mongodb

#list all the volumens you are using in any of your containers
volumes:
  mongo-data:
    driver: local